### ISSUE TITLE
"This power cannot be used while you are in the planar stronghold." in ToB Part

### ISSUE THREAD

**Issue by badungu** [K4thos/EET#6] opened 2016-11-20 00:33 UTC
I played through EET these days, had some crashes (but I think these was engine issues, also got these when I played these games vanilla before...)

But now I have an issue which cant be solved through restarting the executable....
I'm in Saradush and tried the "Pocket Plane" innate spell the first time and everytime I tried to use it I got the error "This power cannot be used while you are in the planar stronghold." and nothing happens...

Used NI and this string is used by K#PP_ADD.SPL, if needed I can provide a savegame... :)

Thanks for the great mod and your work so far... :)

badungu

**Comment by badungu** [comment] 2016-11-21 01:53
Tried it today again, maybe the block in baldur25.bcs should be move to the top of the script and there should be no problem :)

badungu

**Comment by K4thos** [comment] 2017-01-22 03:58
sorry for the late reply. It looks like some mod is blocking this code from executing:
IF
  Global("K#DisableSPIN649","GLOBAL",1)
  !AreaCheckObject("AR4500",Player1)
THEN
  RESPONSE #100
    ReallyForceSpellRES("K#PP_REM",Player1) // No such index
    SetGlobal("K#DisableSPIN649","GLOBAL",0)
    Continue()
END

If you still have that game installed please upload your BALDUR25.BCS and save file - this way I will be able to find which mod broke this script (by checking on which block the script hangs rather than move forward to next block)

**Comment by K4thos** [comment] 2017-02-06 22:00
I've managed to reproduce it (it's a mod conflict). Should be fixed in the next version. As for instability try out installing this version of BP-BGT Worldmap art if you're using that mod: http://gibberlings3.net/forums/index.php?showtopic=28573#entry251479

**Closed by K4thos** 2017-02-06 22:00 UTC
